# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop:0 rgba(172, 182, 229, 0.6),\n"
"    stop:1 rgba(134, 253, 232, 0.6));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 900, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.LoginPlain = QtWidgets.QWidget()
        self.LoginPlain.setObjectName("LoginPlain")
        self.frame = QtWidgets.QFrame(self.LoginPlain)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("QPushButton {\n"
"background-color: #1E2772;\n"
"border-radius: 8px;\n"
"font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16.16px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"font-family: \"Poppins SemiBold\";\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"border: none;\n"
"border-radius: 5px;\n"
"padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #101644;\n"
"    border: 1px solid rgb(0, 35, 35);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #101644;\n"
"    border: 1px solid rgb(0, 15, 15);\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(238, 238, 238);\n"
"border-radius: 8px;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 11px;\n"
"line-height: 16px;\n"
"color: #555555;\n"
"padding-left: 21px;\n"
"padding-top: 3px;\n"
"}\n"
"QLineEdit::placeholderText{\n"
"color: rgb(65, 65, 65);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(206, 20, 388, 152))
        self.label.setStyleSheet("font: 128px  \"Agency FB\";\n"
"background-color:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logo/Penumbra.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(252, 196, 46, 21))
        self.label_2.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 21px;\n"
"color: #555555;\n"
"background-color:none;")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(252, 222, 295, 35))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(250, 277, 46, 21))
        self.label_3.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 21px;\n"
"color: #555555;\n"
"background-color:none;")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 303, 295, 35))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(250, 358, 46, 21))
        self.label_4.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 21px;\n"
"color: #555555;\n"
"background-color:none;")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 384, 295, 35))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(232, 492, 336, 40))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.frame_3.setStyleSheet("background-color: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.frame_5.setStyleSheet("QPushButton:hover{\n"
"border: 0px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 0px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setGeometry(QtCore.QRect(33, 27, 20, 20))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo/options.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.label_4.raise_()
        self.lineEdit_3.raise_()
        self.pushButton.raise_()
        self.stackedWidget.addWidget(self.LoginPlain)
        self.SettingPlain = QtWidgets.QWidget()
        self.SettingPlain.setObjectName("SettingPlain")
        self.frame_4 = QtWidgets.QFrame(self.SettingPlain)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.frame_4.setStyleSheet("QPushButton {\n"
"background-color: #1E2772;\n"
"border-radius: 8px;\n"
"font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16.16px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"font-family: \"Poppins SemiBold\";\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 24px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"border: none;\n"
"border-radius: 5px;\n"
"padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #101644;\n"
"    border: 1px solid rgb(0, 35, 35);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #101644;\n"
"    border: 1px solid rgb(0, 15, 15);\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(238, 238, 238);\n"
"border-radius: 8px;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 11px;\n"
"line-height: 16px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholderText{\n"
"color: rgb(65, 65, 65);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.frame_6.setStyleSheet("background-color: none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.frame_7.setStyleSheet("QPushButton:hover{\n"
"border: 0px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 0px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_3.setGeometry(QtCore.QRect(33, 27, 20, 20))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(351, 179, 111, 21))
        self.label_5.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"color: #555555;\n"
"background-color:none;")
        self.label_5.setObjectName("label_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setGeometry(QtCore.QRect(300, 213, 211, 30))
        self.frame_8.setStyleSheet("background-color: none;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 211, 31))
        self.frame_9.setStyleSheet("QRadioButton {\n"
"    color: #757575;\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 5px;\n"
"    padding-left: 16px;\n"
"    padding-top: 4px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"   background-color: #D9D9D9;\n"
"    color: #1e1e1e;\n"
"}\n"
"\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.radioButton = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton.setGeometry(QtCore.QRect(4, 0, 91, 27))
        self.radioButton.setStyleSheet("font-family: \'Poppins\';")
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_2.setGeometry(QtCore.QRect(111, 0, 91, 27))
        self.radioButton_2.setStyleSheet("font-family: \'Poppins\';")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(369, 104, 61, 21))
        self.label_6.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"color: #555555;\n"
"background-color:none;")
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(337, 133, 125, 27))
        self.lineEdit_4.setStyleSheet("padding: 5px;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setMaxLength(1)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(372, 261, 61, 21))
        self.label_7.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"color: #555555;\n"
"background-color:none;")
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(301, 290, 91, 27))
        self.lineEdit_5.setStyleSheet("padding: 5px;")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setMaxLength(10)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(410, 290, 91, 27))
        self.lineEdit_6.setStyleSheet("padding: 5px;")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setMaxLength(10)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(377, 342, 61, 21))
        self.label_8.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"color: #555555;\n"
"background-color:none;")
        self.label_8.setObjectName("label_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setGeometry(QtCore.QRect(300, 370, 211, 30))
        self.frame_10.setStyleSheet("background-color: none;\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 211, 31))
        self.frame_11.setStyleSheet("QCheckBox {\n"
"    color: #757575;\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QCheckBox::unchecked {\n"
"   color: #757575;\n"
"    background-color: #F5F5F5;\n"
"}\n"
"\n"
"QCheckBox::checked {\n"
"   background-color: #D9D9D9;\n"
"    color: #1e1e1e;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.checkBox = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox.setGeometry(QtCore.QRect(4, 0, 91, 27))
        self.checkBox.setStyleSheet("font-family: \'Poppins\';\n"
"padding-top: 6px;\n"
"padding-left: 2px;\n"
"font-size: 14px;")
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 0, 91, 27))
        self.checkBox_2.setStyleSheet("font-family: \'Poppins\';\n"
"padding-top: 8px;\n"
"font-size: 14px;")
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(328, 403, 40, 12))
        self.lineEdit_7.setStyleSheet("font-size: 10px;\n"
"border-radius: 5px;")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setMaxLength(2)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(436, 403, 40, 12))
        self.lineEdit_8.setStyleSheet("font-size: 10px;\n"
"border-radius: 5px;")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setMaxLength(2)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(297, 441, 213, 40))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.SettingPlain)
        self.GamePlain1 = QtWidgets.QWidget()
        self.GamePlain1.setObjectName("GamePlain1")
        self.frame_2 = QtWidgets.QFrame(self.GamePlain1)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.frame_2.setStyleSheet("QPushButton {\n"
"background-color: #FFFFFF;\n"
"color: #000000;\n"
"text-align: center;\n"
"color: #000000;\n"
"font: 14px \"Poppins\";\n"
"border: none;\n"
"border-radius: 5px;\n"
"padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D9D9D9;\n"
"    color: #1e1e1e;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #D9D9D9;\n"
"    color: #1e1e1e;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(344, 21, 112, 43))
        self.label_9.setStyleSheet("font: 63 8pt\"Poppins SemiBold\";\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 18px;\n"
"line-height: 21px;\n"
"padding-top: 3px;\n"
"color: #555555;\n"
"background-color:none;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"color: #555555;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(360, 72, 35, 35))
        self.label_10.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 21px;\n"
"padding-top: 3px;\n"
"color: #555555;\n"
"background-color:none;\n"
"background-color: #D9D9D9;\n"
"border-radius: 17px;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(405, 72, 35, 35))
        self.label_11.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 21px;\n"
"padding-top: 3px;\n"
"color: #555555;\n"
"background-color:none;\n"
"background-color: #D9D9D9;\n"
"border-radius: 17px;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(622, 163, 169, 274))
        self.plainTextEdit.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"padding: 8px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius: 8px;\n"
"color: #555555;")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(156, 133, 441, 371))
        self.label_15.setStyleSheet("background-color: none;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/Logo/BigChukcha.png"))
        self.label_15.setObjectName("label_15")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(279, 521, 84, 31))
        self.pushButton_5.setStyleSheet("color: #555555;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(392, 521, 84, 31))
        self.pushButton_6.setStyleSheet("color: #555555;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.TimeBK2 = QtWidgets.QLabel(self.frame_2)
        self.TimeBK2.setGeometry(QtCore.QRect(679, 44, 81, 48))
        self.TimeBK2.setStyleSheet("background-color: none;\n"
"font: 57 40px \"SF Pro Rounded\";\n"
"color: rgba(255, 255, 255, 179);")
        self.TimeBK2.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeBK2.setObjectName("TimeBK2")
        self.TimeBK1 = QtWidgets.QLabel(self.frame_2)
        self.TimeBK1.setGeometry(QtCore.QRect(679, 44, 81, 48))
        self.TimeBK1.setStyleSheet("background-color: none;\n"
"font: 57 40px \"SF Pro Rounded\";\n"
"color: rgba(255, 255, 255, 153);")
        self.TimeBK1.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeBK1.setObjectName("TimeBK1")
        self.BK1 = QtWidgets.QLabel(self.frame_2)
        self.BK1.setGeometry(QtCore.QRect(150, 130, 481, 381))
        self.BK1.setStyleSheet("background-color: none;\n"
"color: #1E2772;\n"
"font-size: 70px;\n"
"font-family: \"SF Pro Rounded\";")
        self.BK1.setAlignment(QtCore.Qt.AlignCenter)
        self.BK1.setObjectName("BK1")
        self.stackedWidget.addWidget(self.GamePlain1)
        self.GamePlain2 = QtWidgets.QWidget()
        self.GamePlain2.setObjectName("GamePlain2")
        self.frame_12 = QtWidgets.QFrame(self.GamePlain2)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.frame_12.setStyleSheet("QPushButton {\n"
"background-color: #FFFFFF;\n"
"color: #000000;\n"
"text-align: center;\n"
"color: #000000;\n"
"font: 14px \"Poppins\";\n"
"border: none;\n"
"border-radius: 5px;\n"
"padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D9D9D9;\n"
"    color: #1e1e1e;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #D9D9D9;\n"
"    color: #1e1e1e;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_14 = QtWidgets.QLabel(self.frame_12)
        self.label_14.setGeometry(QtCore.QRect(344, 21, 112, 43))
        self.label_14.setStyleSheet("font: 63 8pt\"Poppins SemiBold\";\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 18px;\n"
"line-height: 21px;\n"
"padding-top: 3px;\n"
"color: #555555;\n"
"background-color:none;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(self.frame_12)
        self.label_13.setGeometry(QtCore.QRect(405, 72, 35, 35))
        self.label_13.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 21px;\n"
"padding-top: 3px;\n"
"color: #555555;\n"
"background-color:none;\n"
"background-color: #D9D9D9;\n"
"border-radius: 17px;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_12)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(622, 163, 169, 274))
        self.plainTextEdit_2.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"padding: 8px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius: 8px;\n"
"color: #555555;")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setGeometry(QtCore.QRect(360, 72, 35, 35))
        self.label_12.setStyleSheet("font-family: \'Poppins\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 21px;\n"
"padding-top: 3px;\n"
"color: #555555;\n"
"background-color:none;\n"
"background-color: #D9D9D9;\n"
"border-radius: 17px;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        self.label_16.setGeometry(QtCore.QRect(19, 207, 291, 251))
        self.label_16.setStyleSheet("background-color:none;")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/Logo/MiniChukcha.png"))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_12)
        self.label_17.setGeometry(QtCore.QRect(328, 207, 291, 241))
        self.label_17.setStyleSheet("background-color:none;")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/Logo/MiniChukcha.png"))
        self.label_17.setObjectName("label_17")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_7.setGeometry(QtCore.QRect(61, 482, 84, 31))
        self.pushButton_7.setStyleSheet("color: #555555;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_8.setGeometry(QtCore.QRect(174, 482, 84, 31))
        self.pushButton_8.setStyleSheet("color: #555555;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_9.setGeometry(QtCore.QRect(376, 482, 84, 31))
        self.pushButton_9.setStyleSheet("color: #555555;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_10.setGeometry(QtCore.QRect(491, 482, 84, 31))
        self.pushButton_10.setStyleSheet("color: #555555;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.TimeMK1 = QtWidgets.QLabel(self.frame_12)
        self.TimeMK1.setGeometry(QtCore.QRect(679, 44, 81, 48))
        self.TimeMK1.setStyleSheet("background-color: none;\n"
"font: 57 40px \"SF Pro Rounded\";\n"
"color: rgba(255, 255, 255, 153);")
        self.TimeMK1.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeMK1.setObjectName("TimeMK1")
        self.TimeMK2 = QtWidgets.QLabel(self.frame_12)
        self.TimeMK2.setGeometry(QtCore.QRect(679, 44, 81, 48))
        self.TimeMK2.setStyleSheet("background-color: none;\n"
"font: 57 40px \"SF Pro Rounded\";\n"
"color: rgba(255, 255, 255, 179);")
        self.TimeMK2.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeMK2.setObjectName("TimeMK2")
        self.MK1 = QtWidgets.QLabel(self.frame_12)
        self.MK1.setGeometry(QtCore.QRect(20, 200, 301, 261))
        self.MK1.setStyleSheet("background-color: none;\n"
"color: #1E2772;\n"
"font-size: 50px;\n"
"font-family: \"SF Pro Rounded\";")
        self.MK1.setAlignment(QtCore.Qt.AlignCenter)
        self.MK1.setObjectName("MK1")
        self.MK2 = QtWidgets.QLabel(self.frame_12)
        self.MK2.setGeometry(QtCore.QRect(330, 200, 301, 261))
        self.MK2.setStyleSheet("background-color: none;\n"
"color: #1E2772;\n"
"font-size: 50px;\n"
"font-family: \"SF Pro Rounded\";")
        self.MK2.setAlignment(QtCore.Qt.AlignCenter)
        self.MK2.setObjectName("MK2")
        self.TimeMK1.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.plainTextEdit_2.raise_()
        self.label_12.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.TimeMK2.raise_()
        self.MK1.raise_()
        self.MK2.raise_()
        self.stackedWidget.addWidget(self.GamePlain2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "КАМУШКИ"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Name"))
        self.label_3.setText(_translate("MainWindow", "Ip:"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter the server\'s IP"))
        self.label_4.setText(_translate("MainWindow", "Port:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter the server\'s port"))
        self.pushButton.setText(_translate("MainWindow", "Start Play"))
        self.label_5.setText(_translate("MainWindow", "Game mode:"))
        self.radioButton.setText(_translate("MainWindow", "One pile"))
        self.radioButton_2.setText(_translate("MainWindow", "Two piles"))
        self.label_6.setText(_translate("MainWindow", "Players:"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "count"))
        self.label_7.setText(_translate("MainWindow", "Range:"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "min"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "max"))
        self.label_8.setText(_translate("MainWindow", "Rules:"))
        self.checkBox.setText(_translate("MainWindow", "        +          "))
        self.checkBox_2.setText(_translate("MainWindow", "         *         "))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "0"))
        self.pushButton_4.setText(_translate("MainWindow", "Create server"))
        self.label_9.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "+0"))
        self.label_11.setText(_translate("MainWindow", "⨯0"))
        self.pushButton_5.setText(_translate("MainWindow", "+0"))
        self.pushButton_6.setText(_translate("MainWindow", "⨯0"))
        self.TimeBK2.setText(_translate("MainWindow", "9:41"))
        self.TimeBK1.setText(_translate("MainWindow", "9:41"))
        self.BK1.setText(_translate("MainWindow", "100"))
        self.label_14.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "⨯0"))
        self.label_12.setText(_translate("MainWindow", "+0"))
        self.pushButton_7.setText(_translate("MainWindow", "+0"))
        self.pushButton_8.setText(_translate("MainWindow", "⨯0"))
        self.pushButton_9.setText(_translate("MainWindow", "+0"))
        self.pushButton_10.setText(_translate("MainWindow", "⨯0"))
        self.TimeMK1.setText(_translate("MainWindow", "9:41"))
        self.TimeMK2.setText(_translate("MainWindow", "9:41"))
        self.MK1.setText(_translate("MainWindow", "0"))
        self.MK2.setText(_translate("MainWindow", "0"))
import Images_rc
import fonts_rc
